all:
	g++ -I../ -I /home/ze.akhter/project/rabbitmq-c/librabbitmq/ -L../../rabbitmq-c/build/librabbitmq/ -L../ send.cpp -lconnection -lrabbitmq -o send
#	g++ -I../ -I /home/ze.akhter/project/rabbitmq-c/librabbitmq/ -L../../rabbitmq-c/build/librabbitmq/ -L../ receive.cpp -lconnection -lrabbitmq -o receive